### ISSUE TITLE
Synching!!

### ISSUE THREAD

**Issue by csrobins** [csrobins/eFRI_LiDAR_Handheld#10]
Synching is an issue:

Need to confirm all synching parts are working properly.  Several aspects to confirm and check:

Maybe only have push capability from the app (very limited pulling).

Update 'lastmodified' ONLY when something actually changes in a row - need to confirm how lastmodified is getting updated in each viewmodel.

ONLY push modified records - since last confirmed update.

CONFIRM back on a successful synch at the server - only then increment the last synched date.

Only update records a the server that have changed.

Manage conflicts at the server?

**Comment by craig-robinson-forsite** [comment]
Version 19 resolves the synch issues - greatly simplifying how it works
