### ISSUE TITLE
validation testing event choice seems odd

### ISSUE THREAD

**Issue by AngusCarrOntario** [csrobins/eFRI_LiDAR_Handheld#22]
Validation testing seems like it fires out of sync with typing. For example, if I go to the easting field, and it is correct, and I remove a character, making it incorrect, then nothing happens. I add the character back in and it reports the error message. Then when I go and do something else, it will eventually retest the validation and clear the message.

**Comment by craig-robinson-forsite** [comment]
Fixed now in version 19
