### ISSUE TITLE
DB Constraint Mismatch - PhotoDistance Maximum

### ISSUE THREAD

**Issue by AngusCarrOntario** [csrobins/eFRI_LiDAR_Handheld#3]
Photo Distance in vsnContractor constrained to 13m, Mobile 15m. Manual (p.42) says 12m, plus add some wiggle room (1m or 3m).

https://github.com/csrobins/eFRI_LiDAR_Handheld/blob/b43192d43423bcc7e264367f81cc6524e7774f39/eLiDAR/Validator/Validator.cs#L396

**Comment by craig-robinson-forsite** [comment]
Done
