### ISSUE TITLE
tblTreeMeasure.DBH12_LV_Range

### ISSUE THREAD

**Issue by AngusCarrOntario** [csrobins/eFRI_LiDAR_Handheld#6]
-- measurement of DBH12 ranged differently by statuscode in ContractorDB
SELECT 'tblTreeMeasure.DBH12_LV_Range'  FROM tblTreeMeasure WHERE (sqrt(DBH1 * DBH2 ) <= 7 OR sqrt(DBH1 * DBH2 ) > 200) AND `TreeStatusCode` IN ( 'L','V' );
SELECT 'tblTreeMeasure.DBH12_DDV_Range' FROM tblTreeMeasure WHERE (sqrt(DBH1 * DBH2 ) <= 10 OR sqrt(DBH1 * DBH2 ) > 200) AND `TreeStatusCode` IN ( 'D','DV');

**Comment by craig-robinson-forsite** [comment]
We need to chat about this one - not sure I understand it
