### ISSUE TITLE
tblTreeMeasure_TreeStatusCodeDBHDBH1DBH2_Limit1 Specific test of DBH vs DBH1/2 not in mobile

### ISSUE THREAD

**Issue by AngusCarrOntario** [csrobins/eFRI_LiDAR_Handheld#7]
-- #MISSING - Specific test of DBH vs DBH1/2 not in mobile
SELECT 'tblTreeMeasure_TreeStatusCodeDBHDBH1DBH2_Limit1',TreeMeasureKey,DBH,DBH1,DBH2 FROM tblTreeMeasure WHERE DBH IS     NULL AND (DBH1 IS     NULL AND DBH2 IS     NULL) AND `TreeStatusCode` IN ( 'L','V','D','DV') ;
SELECT 'tblTreeMeasure_TreeStatusCodeDBHDBH1DBH2_Limit2',TreeMeasureKey,DBH,DBH1,DBH2 FROM tblTreeMeasure WHERE DBH IS NOT NULL AND (DBH1 IS NOT NULL OR  DBH2 IS NOT NULL) AND `TreeStatusCode` IN ( 'L','V','D','DV') ;

**Comment by craig-robinson-forsite** [comment]
Not going to implement DBH1/DBH2 in the interface ??

**Comment by AngusCarrOntario** [comment]
The logic of the 2 measurements is in case of using calipers, two measurements are needed. Neither contractor currently operating will use calipers except in extremely unusual circumstances, so there seems to be no need for including the 2 measurements in the interface. However, the validation matching requirements are necessary in case of future changes. There is no need to implement the validation change at this time, however.
